---
- name: Attempt to create group {{ group }}
  become: true
  ansible.builtin.group:
    name: "{{ group }}"
    state: present

- name: Check {{ group }} group exists in /etc/group
  become: true
  ansible.builtin.command:
    cmd: grep ^{{ group }} /etc/group
  changed_when: false
  ignore_errors: true
  register: group_exists

- name: Get {{ group }} group from /usr/lib/group
  become: true
  ansible.builtin.command:
    cmd: grep ^{{ group }} /usr/lib/group
  changed_when: false
  register: real_group
  when: group_exists.rc != 0

- name: Add {{ group }} group is present to /etc/group
  become: true
  ansible.builtin.lineinfile:
    path: /etc/group
    regexp: '^{{ group }}'
    line: "{{ real_group.stdout }}"
    state: present
  when: group_exists.rc != 0
