---
- include_tasks: group.yaml
  loop: "{{ podman_groups }}"
  loop_control:
    loop_var: group

- name: Create podman user {{ podman_user }}
  become: true
  ansible.builtin.user:
    name: "{{ podman_user }}"
    groups: "{{ podman_groups }}"

  # Lingering is required to keep the user running podman containers after logout
- name: Activate lingering for user {{ podman_user }}
  become: true
  ansible.builtin.command:
    cmd: loginctl enable-linger {{ podman_user }}
    creates: /var/lib/systemd/linger/{{ podman_user }}
