---
- name: General Baseline
  hosts: all

  handlers:
    - name: Reboot
      become: true
      ansible.builtin.reboot:
      vars:
        ansible_user: ansible

  tasks:
    - name: Ansible provisioner user
      become: true
      ansible.builtin.import_role:
        name: ansible_user

    - name: Lockdown SSH
      become: true
      ansible.builtin.import_role: 
        name: geerlingguy.security
      vars:
        security_ssh_allowed_users:
          - ansible
        security_fail2ban_enabled: false
        security_autoupdate_enabled: false
      notify: Reboot

    - name: Install node exporter
      become: true
      ansible.builtin.import_role: 
        name: geerlingguy.node_exporter
      vars:
        node_exporter_options: >
          --collector.disable-defaults
          --collector.cpu
          --collector.meminfo
          --collector.filesystem
          --collector.netdev
          --collector.hwmon
          --collector.stat
          --collector.os
          --collector.time
          --collector.pressure
          --collector.diskstats
          --web.disable-exporter-metrics

    - name: Ensure SSH and Node Exporter port are open
      become: true
      ansible.posix.firewalld:
        port: "{{ item }}"
        permanent: true
        immediate: true
        state: enabled
      with_items:
        - 22/tcp
        - 9100/tcp

    - name: Set timezone to Europe/Dublin
      become: true
      ansible.builtin.timezone:
        name: Europe/Dublin
      notify: Reboot

    - name: Set hostname
      become: true
      ansible.builtin.hostname:
        name: "{{ inventory_hostname }}"
      notify: Reboot
